[package]
name = "server"
version = "0.1.0"
authors = ["alexgnatrow <lesha.gnat@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7"
listenfd = "0.3"
tera="0.11"
log = "0.4.0"
env_logger = "0.6.0"
serde="1"
serde_derive="1"